Merge pull request #30 from ballab1/dev

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,12 +1,88 @@
 #!/bin/bash
 
+#----------------------------------------------------------------------------------------------
+function my.usage()
+{
+    local -i exit_status=${1:-1}
+
+    cat >&2 << EOF
+Usage:
+    $progname [ -h | --help ] 
+              [ -f | --force ]
+              [ -l | --logfile <logName> ]
+              [ -o | --os <osName> ]
+              [ -p | --push ]
+              [ <repoName> <repoName> <repoName> ]
+
+    Common options:
+        -h --help                  Display a basic set of usage instructions
+        -f --force                 force build : do not check if fingerprint exists locally or in registry
+        -l --logfile <logName>     log build results to <logName>
+        -o --os <osName>           specify OS <osName> that will be used. Default all OS types defined
+        -p --push                  always push image to regitry
+
+    build one or more component repos
+
+EOF
+    exit "$exit_status"
+}
+
+#----------------------------------------------------------------------------------------------
+function my.cmdLineArgs()
+{
+    local base="${1:?}"
+    shift
+    local usage='my.usage'
+
+    # Parse command-line options into above variable
+    local -r progname="$( basename "${BASH_SOURCE[0]}" )"
+    local -r options=$(getopt --longoptions "help,Help,HELP,force,push,os:" --options "Hhfpo:" --name "$progname" -- "$@") || "$usage" $?
+    eval set -- "$options"
+
+    local -A opts=()
+    [ "$base" ] && opts['base']="$base" 
+    while true; do
+        case "${1:-}" in
+            -h|--h|--help|-help)  "$usage" 1;;
+            -H|--H|--HELP|-HELP)  "$usage" 1;;
+            --Help|-Help)         "$usage" 1;;
+            -o|--o|--os)          opts['os']="$2"; shift 2;;
+            -f|--f|--force)       opts['force']=1; shift 1;;
+            -p|--p|--push)        opts['push']=1; shift 1;;
+            --)                   shift; break;;
+        esac
+    done
+    
+    local val
+    if [ ${#opts[*]} -gt 0 ]; then
+        local -i i=0
+        for val in "${!opts[@]}"; do
+            [ $(( i++ )) -gt 0 ] && echo -n ' '
+            printf '['\''%s'\'']='\''%s'\' "$val" "${opts[$val]}"
+        done
+    fi
+    echo
+    if [ $# -gt 0 ]; then
+        for val in "$@"; do
+            echo "$val"
+        done
+    fi
+}
+
+#----------------------------------------------------------------------------------------------
+
+declare -i status
+declare -a args
 declare fn=build.wrapper
-if [ "$(env | grep "BASH_FUNC_${fn}%%")" ]; then
-    TOP=/opt
-else
-    declare TOP="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
-    source "${TOP}/libs/loadLibraries.sh"
+
+declare loader="$(dirname "${BASH_SOURCE[0]}")/libs/appenv.bashlib"
+if [ ! -e "$loader" ]; then
+    echo 'Unable to load libraries'
+    exit 1
 fi
+source "$loader"
+appenv.loader "$fn"
 
 : ${BASE_TAG:=latest}
-"$fn" "$TOP" "$@"
+args=$( my.cmdLineArgs "$TOP" "$@" ) && status=$? || status=$?
+[ $status -eq 0 ] && "$fn" ${args[@]} 
diff --git a/registryReport b/registryReport
--- a/registryReport
+++ b/registryReport
@@ -1,11 +1,86 @@
 #!/bin/bash
 
-declare fn=registry.reportCatalog
-if [ "$(env | grep "BASH_FUNC_${fn}%%")" ]; then
-    TOP=/opt
-else
-    declare TOP="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
-    source "${TOP}/libs/loadLibraries.sh"
-fi
+#----------------------------------------------------------------------------------------------
+function my.usage()
+{
+    local -i exit_status=${1:-1}
 
-"$fn" "$@"
+    cat >&2 << EOF
+Usage:
+    $progname [ -h|--help ] | [ --output <filename> ]  <repository> | <repository> | <repository>
+
+    Common options:
+        -h --help                 Display a basic set of usage instructions
+        -o --output <filename>    name of file to output
+
+    Report the contents of the name docker repository from the registry, if no repositories are name, all are reported
+    The name of the docker registry should not be included in the repository name.
+
+EOF     exit "$exit_status"
+}
+
+#----------------------------------------------------------------------------------------------
+function my.cmdLineArgs()
+{
+    local usage='my.usage'
+
+    # Parse command-line options into above variable
+    local -r progname="$( basename "${BASH_SOURCE[0]}" )"
+    local -r options=$(getopt --longoptions "help,Help,HELP,output:" --options "Hho:" --name "$progname" -- "$@") || "$usage" $?
+    eval set -- "$options"
+
+    local -A opts=()
+    while true; do
+        case "${1:-}" in
+            -h|--h|--help|-help)  "$usage" 1;;
+            -H|--H|--HELP|-HELP)  "$usage" 1;;
+            --Help|-Help)         "$usage" 1;;
+            -o|--o|--output)      opts['output']="$2"; shift 2;;
+            --)                 shift; break;;
+        esac
+    done
+    
+    local val
+    if [ ${#opts[*]} -gt 0 ]; then
+        local -i i=0
+        for val in "${!opts[@]}"; do
+            [ $(( i++ )) -gt 0 ] && echo -n ' '
+            printf '['\''%s'\'']='\''%s'\' "$val" "${opts[$val]}"
+        done
+    fi
+    echo
+    if [ $# -gt 0 ]; then
+        for val in "$@"; do
+            echo "$val"
+        done
+    fi
+}
+
+#----------------------------------------------------------------------------------------------
+function formatTextReport()
+{
+    declare -r TOOLS="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )" 
+
+    docker run --rm \
+               --volume "$TOOLS":/home/groovy/scripts \
+               --environment "JSON=registryReport.json" \
+               --workdir /home/groovy/scripts \
+               groovy:2.6-jre-alpine \
+               groovy registryReport.groovy  
+}
+
+#----------------------------------------------------------------------------------------------
+
+declare -i status
+declare -a args
+declare fn=registry.reportCatalog
+
+declare loader="$(dirname "${BASH_SOURCE[0]}")/libs/appenv.bashlib"
+if [ ! -e "$loader" ]; then
+    echo 'Unable to load libraries'
+    exit 1
+fi
+source "$loader"
+appenv.loader "$fn"
+args=( $( my.cmdLineArgs "$@" ) ) && status=$? || status=$?
+[ $status -eq 0 ] && "$fn" ${args[@]}
